# Generated by Django 4.2.5 on 2023-10-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alergenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergeno_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_fornecedor', models.CharField(max_length=14, unique=True)),
                ('raz_soc_fornecedor', models.CharField(max_length=100)),
                ('cep_fornecedor', models.CharField(max_length=8)),
                ('logradouro_fornecedor', models.CharField(max_length=100)),
                ('numero_fornecedor', models.CharField(max_length=10)),
                ('bairro_fornecedor', models.CharField(max_length=100)),
                ('cidade_fornecedor', models.CharField(max_length=100)),
                ('estado_fornecedor', models.CharField(max_length=2)),
                ('telefone_fornecedor', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_contato_fornecedor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('tamanho_quantidade', models.CharField(blank=True, max_length=50, null=True)),
                ('disponibilidade', models.BooleanField(default=True)),
                ('imagem_url', models.CharField(blank=True, max_length=255, null=True)),
                ('tempo_preparo', models.IntegerField(blank=True, null=True)),
                ('receita', models.TextField(blank=True, null=True)),
                ('informacoes_nutricionais', models.TextField(blank=True, null=True)),
                ('classificacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('data_inclusao', models.DateField(blank=True, null=True)),
                ('estoque', models.IntegerField(blank=True, null=True)),
                ('restricoes_dieteticas', models.CharField(blank=True, max_length=100, null=True)),
                ('sazonalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_pedido_identificador', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.categoria')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.fornecedores')),
            ],
        ),
    ]
