# Generated by Django 4.2.5 on 2023-10-08 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(max_length=100)),
                ('nome_contato', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('observacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='bairro_fornecedor',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='cep_fornecedor',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='cidade_fornecedor',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='estado_fornecedor',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='logradouro_fornecedor',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='nome_contato_fornecedor',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='numero_fornecedor',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='telefone_fornecedor',
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='contato_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.contato'),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='endereco_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.endereco'),
        ),
    ]
