# Generated by Django 4.2.5 on 2023-10-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_contato_endereco_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedores',
            new_name='Fornecedor',
        ),
    ]
