# Generated by Django 4.2.5 on 2023-10-17 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_fornecedor_contato_fk_delete_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(max_length=100)),
                ('nome_contato', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=100)),
                ('fornecedor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.fornecedor')),
            ],
        ),
    ]
